apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dbxgo
  name: dbxgo
  namespace: kube-middleware
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: dbxgo
  template:
    metadata:
      labels:
        app: dbxgo
    spec:
      containers:
        - env:
            - name: SOURCE_MYSQL_ADDR
              value: '127.0.0.1:3306'
            - name: SOURCE_MYSQL_USER
              value: root
            - name: SOURCE_MYSQL_PASSWORD
              value: 123456
            - name: SOURCE_MYSQL_EXCLUDE_TABLE_REGEX
              value: "mysql.*,information_schema.*,performance_schema.*,sys.*"
          image: zhiqiangwang/dbxgo:latest
          imagePullPolicy: Always
          name: dbxgo
          resources:
            limits:
              cpu: '1'
              memory: 500Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
